import { NextRequest, NextResponse } from "next/server";
const COLLECTION_BUYERS = new Set([
  "juniorzacharybitton48@gmail.com",
  "layelmister@gmail.com",
  "clarensjeanjacques0@gmail.com",
  "jeffalcime.pro@gmail.com",
  "avatarinvestisment2025@gmail.com",
  "herlotjoseph@yahoo.com",
  "ledatushilaire.75@gmail.com",
  "alyngilet@gmail.com",
  "jeanandersen498@gmail.com",
  "skesnove@gmail.com",
  "milcentrolp6@gmail.com",
  "stehmoc7@icloud.com",
  "coast.squinty_2n@icloud.com",
  "babasdiof@gmail.com",
  "louisemabob@gmail.com",
  "bethsaidaisrael648@gmail.com",
  "cheryrivaldo64@gmail.com",
  "levelprm@gmail.com",
  "pierredjeyson6@gmail.com",
  "benjaminfarley55@yahoo.fr",
  "vkervens97@gmail.com",
  "alphonsedorvilus@gmail.com",
  "wildsaintcyr@gmail.com",
  "formonvilcliford81@gmail.com",
  "clover_nome.3t@icloud.com",
  "jamesvico92@gmail.com",
  "johnwoodidorphyl@gmail.com",
  "makensonjassinthe264@gmail.com",
  "gilleslesly1@gmail.com",
  "derismasmith69@gmail.com",
  "charlesennery19@gmail.com",
  "damarahestelleprevost@gmail.com",
  "dayoolove@icloud.com",
  "merlinkasparovjean@gmail.com",
  "b.loubens10@gmail.com",
  "rodriguemesidor005@gmail.com",
  "pierremickael418@gmail.com",
  "joinicelucasjuan@gmail.com",
  "sauveurjosephisaie@gmail.com",
  "jozamasimeonjoseph@gmail.com",
  "tarzantaxi12@gmail.com",
  "ansyrichecarde2@icloud.com",
  "davidanalce@icloud.com",
  "belange201088@gmail.com",
  "thotho4778@gmail.com",
  "jeanmarymarly@gmail.com",
  "stevensonb945@gmail.com",
  "jeankenleyy@gmail.com",
  "pauldavid907@gmail.com",
  "maphneyfils35@gmail.com",
  "willsvalendy@gmail.com",
  "pybarosy@gmail.com",
  "katoutou3@gmail.com",
  "abygalremy1@gmail.com",
  "leslysidort@gmail.com",
  "sebienestor@icloud.com",
  "etienneroodjerry960@gmail.com",
  "manifesto.vip50@gmail.com",
]);
export async function POST(req: NextRequest) {
  const { email } = await req.json();
  if (!email || typeof email !== "string") return NextResponse.json({ valid: false });
  return NextResponse.json({ valid: COLLECTION_BUYERS.has(email.trim().toLowerCase()) });
}